### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by prashantvc** [AvaloniaUI/AvaloniaVSCode#5]
- [x] Extension Icon
- [x] Color scheme
- [x] Dependencies
- [x] README file
- [x] Lincense file
- [x] Repository/Issue links
- [x] Verify version number
- [x] Publisher and author details
